---
title: "Lab 07 - Linear Regression"
author: NAME HERE
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: simplex
    number_sections: false
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

## 0 load the package and suppress scientific notation 
```{r}
# load packages 
library(ggplot2)
# not display scientific notation
options(scipen=999)
```

## 1 create a data frame 

```{r}
# read data from a csv file 
housing.df <- read.csv("ameshousing.csv")
# first six rows 
head(housing.df)
# column names 
names(housing.df)
```

## 2 identify thresholds of 4 bins with an equal number of observations 
```{r}
thresholds_4<- quantile(housing.df$Gr_Liv_Area, probs = c(0,0.25,0.5,0.75,1)) 
```

## 3 bin Gr_Liv_Area   
```{r}
# remove the names of a named vector 
bins <- unname(thresholds_4) 
bins

# bin Gr_Liv_Area 
Gr_Liv_Area_bin <- .bincode(housing.df$Gr_Liv_Area, bins, include.lowest = TRUE)
Gr_Liv_Area_bin
# first six values of Gr_Liv_Area_bin
head(Gr_Liv_Area_bin)

# data type of Gr_Liv_Area_bin
class(Gr_Liv_Area_bin)

```

## 4 fit a regression model with an ordinal categorical predictor 
```{r}
lm <-lm(SalePrice ~ as.factor(Gr_Liv_Area_bin),data=housing.df)
summary(lm)
```

## 5 calculate the mean of Sale Price for each value in Gr_Liv_Area_bin
```{r}
# mean of SalePrice for each value in Gr_Liv_Area_bin 
tapply(housing.df$SalePrice, Gr_Liv_Area_bin, mean)

# group mean difference between category 2 and category 1
# 2-1
130211-105448

# group mean difference between category 3 and category 1
150122-105448

# group mean difference between category 4 and category 1
164648-105448
```

## 6 plot the mean of Sale Price for each value in Gr_Liv_Area_bin
```{r}
ggplot(housing.df, aes(x=Gr_Liv_Area_bin, y=SalePrice)) + 
  geom_bar(stat = "summary", fun = "mean")

```
